apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht11-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dht11-server
  template:
    metadata:
      labels:
        app: dht11-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sensortype
                operator: In
                values:
                - dht11
      containers:
        - name: dht11-server
          image: alicey/raspi-dht11-server:latest
          securityContext:
            privileged: true
          env:
            - name: PIN
              value: "23"
---
apiVersion: v1
kind: Service
metadata:
  name: dht11-svc
spec:
  ports:
  - nodePort: 32121
    port: 32121
    protocol: TCP
  selector:
    app: dht11-server
  type: NodePort
