apiVersion: v1
kind: Pod
metadata:
  name: raspi-iot-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sensortype
            operator: In
            values:
            - dht11
  containers:
    - name: iot-test
      image: alicey/raspi-iot-test:latest
      securityContext:
        privileged: true
  
